# deployment/_config.yml
# Basic site settings
title: AI FUUTBOL
description: >-
  A short tagline or description.

# If this repo is published at username.github.io/repo
baseurl: "/repo"     

# If you want to use a built-in theme:
theme: minima       

# If you have markdown pages you'd like processed:
markdown: kramdown  
